export const OUTFIT_DETAILS_REQUEST = "OUTFIT_DETAILS_REQUEST";
export const OUTFIT_DETAILS_SUCCESS = "OUTFIT_DETAILS_SUCCESS";
export const OUTFIT_DETAILS_FAILED = "OUTFIT_DETAILS_FAILED";
export const OUTFIT_DETAILS_RESET = "OUTFIT_DETAILS_RESET";
