export const OUTFIT_DETAILS_REQUEST = "OUTFIT_DETAILS_REQUEST";
export const OUTFIT_DETAILS_SUCCESS = "OUTFIT_DETAILS_SUCCESS";
export const OUTFIT_DETAILS_FAILED = "OUTFIT_DETAILS_FAILED";
export const OUTFIT_DETAILS_RESET = "OUTFIT_DETAILS_RESET";

export const OUTFIT_FILTER_IMAGES_REQUEST = "OUTFIT_FILTER_IMAGES_REQUEST";
export const OUTFIT_FILTER_IMAGES_SUCCESS = "OUTFIT_FILTER_IMAGES_SUCCESS";
export const OUTFIT_FILTER_IMAGES_FAILED = "OUTFIT_FILTER_IMAGES_FAILED";
